title: Isuru Nuwanthilaka's Blog
email: isurunuwanthilaka@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I talk about different technologies and journey of life.
  This site consists of my own thoughts and this doesn't represent the views of company I work for.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isurunuwanthilaka.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  isurunuwnathilaka

#Author
author:
  name : Isuru Nuwanthilaka
  email: isurunuwanthilaka@gmail.com

#Social Media
minima:
  social_links:
    facebook: isurunuwanthilaka
    github : isurunuwanthilaka
    stackoverflow : isurunuwanthilaka
    linkedin : isurunuwanthilaka

    youtube_channel: UCWT6lIKNUN-1F-WxIov4NUQ
    youtube_channel_name: Isuru Nuwanthilaka

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Disqus Comments
disqus:
    shortname: https-isurunuwanthilaka-github-io

# Google Analytics
google_analytics: G-13KD5X904R

gems:
  - jekyll-paginate

paginate: 5
paginate_path: posts/page:num/

