title: Isuru Nuwanthilaka
email: isurunuwanthilaka@gmail.com
description: "Personal blog"
url: "https://isurunuwanthilaka.github.io"
baseurl: ""
github_username: isurunuwanthilaka

#Author
author:
  name: Isuru Nuwanthilaka
  email: isurunuwanthilaka@gmail.com

#Social Media
minima:
  social_links:
    facebook: isurunuwanthilaka
    github: isurunuwanthilaka
    stackoverflow: "9559501"
    linkedin: isurunuwanthilaka
    youtube_channel: UCWT6lIKNUN-1F-WxIov4NUQ
    youtube_channel_name: Isuru Nuwanthilaka

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Google Analytics
google_analytics: G-13KD5X904R

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
