title: Isuru Nuwanthilaka's Blog
email: isurunuwanthilaka@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  isurunuwnathilaka

#Author
author:
  name : Isuru Nuwanthilaka
  email: isurunuwanthilaka@gmail.com

#Social Media
social:
  facebook: isurunuwanthilaka

# Build settings
theme: minima
plugins:
  - jekyll-feed