title: Isuru Nuwanthilaka's Blog
email: isurunuwanthilaka@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I talk about technologies, life and buddhism.
  This site consists of my own thoughts and this doesn't represent views of company I represent.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  isurunuwnathilaka

#Author
author:
  name : Isuru Nuwanthilaka
  email: isurunuwanthilaka@gmail.com

#Social Media
social:
  facebook: isurunuwanthilaka

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Disqus Comments
comment : true
disqus:
    shortname: https-isurunuwanthilaka-github-io


# Google Analytics
google_analytics: G-13KD5X904R

# Facebook Like
facebook_like: true
